Repository mathias-onu/eclesia-worship, pull requests merged in 2023-11, with the labels that each got.

#97 Song is now formatted correctly and mongoose is updated.
  .github/workflows/build-deploy.yml
  .github/workflows/build-test.yml
  README.md
  cypress.config.ts
  package-lock.json
  package.json
  server.js
  src/app/features/presentation-view/components/presentation-view/presentation-view.component.scss
  src/app/shared/pipes/format-song.pipe.ts
  src/environments/environment.development.ts
Labels: frontend, backend

#103 New deployment configurations
  .github/workflows/build-deploy.yml
  .github/workflows/build-test.yml
  .gitignore
  README.md
  package.json
Labels: devops

#104 New deployment configurations
  .github/workflows/build-deploy.yml
  .github/workflows/build-test.yml
  .gitignore
  README.md
  package.json
Labels: frontend, backend, devops

#105 Minor deployment configurations
  .github/workflows/build-deploy.yml
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#106 Minor deployment configurations
  .github/workflows/build-deploy.yml
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#107 changed order of building for deployment (debugging deployment issues)
  .github/workflows/build-deploy.yml
Labels: devops

#108 Minor deployment configurations
  .github/workflows/build-deploy.yml
Labels: devops

#109 Temporary deployment workaround
  .github/workflows/build-deploy.yml
  .gitignore
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#110 Temporary deployment workaround
  .github/workflows/build-deploy.yml
  .gitignore
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#111 added custom build script for digitalocean deployment
  .github/workflows/build-deploy.yml
  .gitignore
  package.json
Labels: devops

#112 added custom build script for digitalocean deployment
  .github/workflows/build-deploy.yml
  .gitignore
  package.json
Labels: devops

#113 deleted the dist folder
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#114 deleted the dist folder
  dist/client/130.f1d1055d40baaa2e.js
  dist/client/3rdpartylicenses.txt
  dist/client/893.2289936917e7decd.js
  dist/client/assets/logo/logo.svg
  dist/client/common.9861154e0040fcee.js
  dist/client/favicon.ico
  dist/client/index.html
  dist/client/main.914a15c3af341677.js
  dist/client/polyfills.9235a755e281251e.js
  dist/client/runtime.db0c7c2d37b78107.js
  dist/client/styles.7f3d79dac24764fa.css
  dist/client/~partytown/debug/partytown-atomics.js
  dist/client/~partytown/debug/partytown-media.js
  dist/client/~partytown/debug/partytown-sandbox-sw.js
  dist/client/~partytown/debug/partytown-sw.js
  dist/client/~partytown/debug/partytown-ww-atomics.js
  dist/client/~partytown/debug/partytown-ww-sw.js
  dist/client/~partytown/debug/partytown.js
  dist/client/~partytown/partytown-atomics.js
  dist/client/~partytown/partytown-media.js
  dist/client/~partytown/partytown-sw.js
  dist/client/~partytown/partytown.js
Labels: devops

#118 renamed the deploy workflow
  .github/workflows/deploy.yml
Labels: devops

#129 reorganized the backend files
  server.js
  server/controllers/index.js
  server/controllers/playlists.js
  server/controllers/songs.js
  server/routes/index.js
  server/routes/playlists.js
  server/routes/songs.js
Labels: backend

#132 fixed font size resetting on refresh bug
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.ts
Labels: bug, frontend

#133 reorganized the backend file structure and fixed a frontend bug
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.ts
  server.js
  server/controllers/index.js
  server/controllers/playlists.js
  server/controllers/songs.js
  server/routes/index.js
  server/routes/playlists.js
  server/routes/songs.js
Labels: bug, frontend, backend

#137 fixed build script issue in production
  package.json
Labels: backend

#138 fixed build script issue in production
  package.json
Labels: backend

#139 fixed client dist path access in production
  server.ts
Labels: backend

#140 fixed client dist path access in production
  server.ts
Labels: backend

#144 Removed mongodb collation
  server/controllers/playlists.ts
  server/controllers/songs.ts
Labels: backend

#145 Removed MongoDB collation
  server/controllers/playlists.ts
  server/controllers/songs.ts
  server/models/Playlist.ts
  server/models/Song.ts
Labels: bug, backend

#147 decreased line-height for song and bible text slides
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.html
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.scss
Labels: frontend, feature
