Repository mathias-onu/eclesia-worship, pull requests merged in 2023-12, with the labels that each got.

#162 Playlists now return the songs id
  client/app/core/services/songs.service.ts
  client/app/features/controller-view/components/playlist-search-dialog/playlist-search-dialog.component.html
  client/app/features/controller-view/components/playlist-search-dialog/playlist-search-dialog.component.ts
  client/app/features/controller-view/components/playlist/playlist.component.ts
  client/app/shared/models/playlist.model.ts
  client/app/shared/models/song.model.ts
  client/app/shared/pipes/format-playlist.pipe.ts
  client/app/shared/pipes/format-song.pipe.ts
  cypress/e2e/presentation-flows.cy.ts
  server/controllers/playlists.ts
  server/controllers/songs.ts
  server/routes/songs.ts
Labels: bug, frontend, backend

#166 Added select presenter background image feature
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.html
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.scss
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.ts
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.html
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.scss
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.ts
Labels: frontend, feature

#167 Added select presenter background image feature
  client/app/core/services/songs.service.ts
  client/app/features/controller-view/components/playlist-search-dialog/playlist-search-dialog.component.html
  client/app/features/controller-view/components/playlist-search-dialog/playlist-search-dialog.component.ts
  client/app/features/controller-view/components/playlist/playlist.component.ts
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.html
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.scss
  client/app/features/controller-view/components/pre-presentation/pre-presentation.component.ts
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.html
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.scss
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.ts
  client/app/shared/models/playlist.model.ts
  client/app/shared/models/song.model.ts
  client/app/shared/pipes/format-playlist.pipe.ts
  client/app/shared/pipes/format-song.pipe.ts
  cypress/e2e/presentation-flows.cy.ts
  server/controllers/playlists.ts
  server/controllers/songs.ts
  server/routes/songs.ts
Labels: frontend, feature

#168 Fixed property misnaming
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.ts
Labels: bug, frontend

#169 Fixed property misnaming
  client/app/features/presentation-view/components/presentation-view/presentation-view.component.ts
Labels: bug, frontend

#173 Added better formatting for songs
  client/app/shared/pipes/format-song.pipe.ts
Labels: bug, frontend

#176 Removed unnecessary sync songs call
  client/app/features/controller-view/components/songs/songs.component.ts
Labels: bug, frontend

#177 Fixed song formatting pipe and removed unnecessary sync songs call
  client/app/features/controller-view/components/songs/songs.component.ts
  client/app/shared/pipes/format-song.pipe.ts
Labels: bug, frontend
